# Generated by Django 5.0.3 on 2024-04-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_books_count', models.IntegerField(default=0)),
                ('inactive_books_count', models.IntegerField(default=0)),
                ('active_authors_count', models.IntegerField(default=0)),
                ('inactive_authors_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
